### ISSUE TITLE
New memory views are not shown until after refresh

### ISSUE THREAD

**Issue by benmcmorran** [haneefdm/memview#2]
I'm using the `cppdbg` debug adapter and noticed that after the first memory view, subsequent memory views aren't shown until after the view is manually refreshed.

Repro steps:

1. With a `cppdbg` debug session active, open the URI `vscode://haneefdm.memview/0x20000670`.
2. Confirm that the memory view appears at the correct address.
3. Open the URI `vscode://haneefdm.memview/0x20000814`.
4. Note that the memory viewer still only shows a single memory view.
![image](https://user-images.githubusercontent.com/6981284/187268172-b98ec2d8-5532-4e4e-8cf9-36ff4ff34660.png)
5. Click the refresh button in the memory viewer.
6. Note that the memory viewer now shows both memory views.
![image](https://user-images.githubusercontent.com/6981284/187268204-14e725f7-6a09-4ad5-989c-dc18424e886a.png)

Other details:

memview extension version 0.0.7
C/C++ extension version 1.11.5
VS Code version 1.70.0

**Comment by haneefdm** [comment]
Thanks @benmcmorran for trying it out.  When the second view was added, was the program stopped or in another state (not running or not even there)

I did see an issue that if you added a view when the program was not in a stopped state, I was not letting the Webview know that there was a new view available. Question is do I switch the current view at the same time or not. I'd think that if there is already a view, then don't switch views as it will be empty. But update the Menu to reflect the additional view.

**Comment by haneefdm** [comment]
Note that I am anticipating multiple debug sessions and there is some convoluted logic trying to figure out the correct session to attach to when not sessionId is provided. There was also bug there.

**Comment by benmcmorran** [comment]
I was able to repro with the debug session in a stopped state when both URIs were opened, but I'll try other scenarios to see if the behavior is different.

**Comment by haneefdm** [comment]
I am working on an update. Testing it right now.

**Comment by haneefdm** [comment]
Just pushed an update to the marketplace. It *should* work better with the debug session paused or otherwise. Paused of course is a better experience.

BTW, I have not updated Cortex-Debug myself as I was wanting the API to settle. You may be blazing the trail here :-) The only place I plan to use it is in the RTOS view(s) and obsolete the memory viewer built into Cortex-Debug is that is very plane/jane and lacks many features that are over here.

**Comment by haneefdm** [comment]
Closing this.

FYI: We are in the process of moving this repo to https://github.com/mcu-debug/memview

The transition is almost complete except for moving issues. The new extension(s) are now live.

**Comment by benmcmorran** [comment]
Thanks! Sorry I forgot to comment after your update.
