### ISSUE TITLE
When exiting debug or no mem that needs to be displayed, the mem starting with 0 will still be displayed

### ISSUE THREAD

**Issue by hongshui3000** [haneefdm/memview#4]
When exiting debug or no mem that needs to be displayed, the mem starting with 0 will still be displayed
![image](https://user-images.githubusercontent.com/25566498/187650048-afb6691c-25a7-4c82-acd7-51fa20c31b79.png)

**Comment by haneefdm** [comment]
That is intentional. I am showing an example with instructions. Did you read what on the right side under decoded bytes?

**Comment by haneefdm** [comment]
But why would it show that if you are exiting debug? It shows this when there are zero user-created views exist.
